[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "66c1e370cd2ef24d5045fbe988bde7f831c66935"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "82c3d2f3afbc1dde5f45c9520644c1f0783451aafcf58a1757a08ecd3d11b821"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.aarch64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "c4e48b4b3b58096ac473325977768eef874f5b1f"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "1e8f385ac9657fb2e62a3096dfd49b4b3816a38489e5224b97b91b61be8910a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.aarch64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "603a93a656d727808fffbcdb71ed37f4f1cde7b5"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "faa23bf124858fd961feb0d944795e1b6668d2fc81e6d71d36ff1e81b1cd7bb8"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.aarch64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4992fb3df8dc0f46044465584bc5fbb8524ae8de"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "a400bb169afa6ba8c81d35c86ab021f456e27c3a047a9beeb4730dce7c63bd19"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.armv6l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4def04d3227086d5cdaf57397600860a8679f68c"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "6de92f824d592392844825db5ccdd1e739647229f686ec23d6be6fbeaaf48061"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.armv6l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5a9a722beda6f3a3a2af0baf08a36542ae0f1fc8"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "c122f78a51ef75e33e6f46709fbc63b881e693e4900c559b91baa79de60a9e75"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.armv7l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf08cf23b78451f4c2a21084a2012a129b205ed6"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "89201d887a1a992546d8ca967ccb9e993d7c1d47d526483a900ab47eeea7c58f"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.armv7l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "f1c35af554e12a63481ac822fe595cef12ace9f7"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "215bfc584d69b1284459a7433b97f0cbd73fad6937cd564369c3fb7163800492"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.i686-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "8afabcb0bdb7048f8b8006cc4c2905ff654fc3ee"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "ecfba71607a04ff3e191ae3956c8c62bff3deb20c5f480841dfadc06026f5297"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.i686-linux-musl.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "e8492acf68f85e0050ea9c5f91dba79bcedb1bc6"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "99ccc2b9f8c105648ecc03b849c78fed1d76d3b6a220c65cdf813835adb44344"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.i686-w64-mingw32.tar.gz"
[[OpenLibm]]
arch = "powerpc64le"
git-tree-sha1 = "dde41e02167678711c6ce9ecf9504cb18ee7bab6"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "2b6d31ba2f9de98f342430f7b107451dad2a273eb6fc2ddf713e1f745cb0f6d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.powerpc64le-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "418e651553e5b518b07ccec0a08b04defdb110d6"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "ea143c65240b53e1cb217100be4db3703c8af828cb787ee17172e0f497f048f9"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.x86_64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "f97c15cfb7ea644fa8fb702fa97a5c17773d2325"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "2884c8ed2dd1157216df98181aec1fad5e720b03cd58a056051323bfb5428f2a"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.x86_64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "92759a38bbca097ae7533a185d2e072bbe56a244"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "3d2046ad6cd2de26b30a8f6004e531719d0199a50317e1d9e09ed32ec4a8febd"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.x86_64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "f5d651bb721f3ea4fdca577dbb08cf571d9dd780"
os = "freebsd"

    [[OpenLibm.download]]
    sha256 = "f26547499b65f252ade3695d3695fa9f02832bf2e7756df115697a1d1cd3042f"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.x86_64-unknown-freebsd.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "6f8bca28bc6ffbe04f46abc4c7774f485f3ed679"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "a1e5d8b4f2b15fa3e2620bf6a3225fcbbdf66f3741e26ea4d596b54237be35e6"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+1/OpenLibm.v0.7.5.x86_64-w64-mingw32.tar.gz"
