[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "89647ed99cd16ac78a4fe7bc8c32a645335bb1ee"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "c28ba1323a5f869c49929b65fdda4f47c61c1cea9b5accfd309b91cea353af55"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.aarch64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "5cf494bfd0bede3d359408db2d8ea5cf4a5cd9e1"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "b503233baf1ac3e70bc43ce2d2e60d6fb4ea96090d7e4221299f5c24a3cc3590"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.aarch64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "33e3d6070600f91d1cb1a0630e4c0ffac4542ba2"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "0336913afcb2a1faa65269dcaf7e78bebb80635cfb78f8b3d054dff795658798"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.aarch64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce19868a2a4b3ba52061f14ae4732235bd2a93ff"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "92adc2f397976dad66ebf4b4a2237b900af22f9e69e013417253e60b9c3a533e"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.armv6l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d49584caea19d60ec11a2a1ba6c2c7aeb0a3d978"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "6f0145ffa291e08cb7419593aa7adf6eb51d8a4af001fc351f587d90c51e9b8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.armv6l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f19a18a4041bd9d44f327ab8386034b94e07cbe5"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "6346bac51a6626514c3ab40fb8cb116529f7ada6487bc648e70eb32913379226"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a18b63cb00fdec8476a189abc47d33d9bb51ec4b"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "b9eb16541faa24667797792ebe1c59248f678c2a1e9f1105189d4b8dfaea353d"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.armv7l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "dfb0291e7dbc0e5ab9fc42863ccd9a887b3e71a4"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "ead820f136b7a42799a6032d628c942ce8689f51322674a25ea10771a4b10845"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.i686-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "e27f38f44a405cb3815f232537ec49edb462a35b"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "b38218b25c4e2b3612e19a1cf286690ccc591b17ef1e6651cb070520ae212c0d"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.i686-linux-musl.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "907fa736f69ba7f70460ad0b7a537be85cddb71c"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "288c400be3b9069da25131aeeacc567c952ea4370576f3cc2a802e2fbf68c713"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.i686-w64-mingw32.tar.gz"
[[OpenLibm]]
arch = "powerpc64le"
git-tree-sha1 = "82401dad749931d9eaabde4410fe69fe7151c74b"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "e875e152a5e180d2b4c3a6744ac7a1963a91f2ed23733af588d802182c7894ac"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.powerpc64le-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "43529ce141776a520d86711d9207e2f3c9638240"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "553d7d75ba483c24923e09fa01c08f6d3544a6a393cae6e72c19eff9f41cb678"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.x86_64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "0771048a09897bcdb2f8a829a8d8f5d38cfa0144"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "40b6303e6c7b918246e32a4a65af543d342777ba1f17128899bde9b64e928a81"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.x86_64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "02e6736e0648ad19aecb041062ce1c34f9dbe6e6"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "dc2b8b46d306c6b7ff8982a003df43c0df248173ac3dd7e952f17f4eded71ec7"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.x86_64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "fae008048989656b9071b9a242b7170821f76fc9"
os = "freebsd"

    [[OpenLibm.download]]
    sha256 = "709ce4cf7f99cb328e2384c844fc550d806c12c9b5c2e5f5c1b2004ca8153291"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "85bde5ba84b80689581f62aebd82682d13fc6566"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "132b0cd7458780c764192469f2ec19186f8bf645d2e2da4b5195a6d4bc1766a7"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.0+0/OpenLibm.v0.8.0.x86_64-w64-mingw32.tar.gz"
