[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "0422ad3bea1585243130b23088ba348000cb4302"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "abef91ed79646f26b6f654d1e8ffbcaebe2cc347bc789578758d6c8ad32584e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.aarch64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "4ec775bac60b85cf1ea5f0264098e408fd247db0"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "0861919ee744d539052c627870b218dc71754e3971859481e12b5dfe23d635f7"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.aarch64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "e87f4cc154db52e9bf4095ede8166c93cf076048"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "5ff6a56a707856e6ec200f57140a6a472b6b9f9380554a85259b6611e5efed4d"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.aarch64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2079b8b6081c5734e985225473fbb96059b9bd6b"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "c8d0efa099af70ec636354e64b375aa17b1100221dc786a12f3fd6a533d05ef1"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.armv6l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4130e729b34c9c935d31cf42d93675cae8042d27"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "464e8a9b9776c162d7d5860252d2c8ae7dc6400b4d6f4f08992d0aad182f20d2"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.armv6l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f16203e725abcc78d5146aad116df34c7905fcff"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "1dec802fd1d3622bf70fd84a429af783d7b05dbce9e1336a1ce93d75a04b2ca3"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.armv7l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b99367dd057b25c939f50ef7fd29caf81c22760"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "fa9df6d61c6cbd22bf2da822a58bb6001482c1e506c12668ae7e69d926e8020e"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.armv7l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "900cdfd8817e07dc39efc5bef54020ae3c8d5212"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "6f2d3c9c20b377d1adf0f275b85046e4eba1256001011b703d6d507e8621cb1a"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.i686-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "43530edc67322e230f54ef116e47daf17e4c658d"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "a831bf8659c738e92e681a76338a28bafdcac7497a8409983dab9ba2236fa3a1"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.i686-linux-musl.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "006ed565a3c639393b7799ea12a5a33a075f72b8"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "53d4cfb5dfaff3fc3654fd757e776120b4b85eb6733b4ae35006db049f0f343a"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.i686-w64-mingw32.tar.gz"
[[OpenLibm]]
arch = "powerpc64le"
git-tree-sha1 = "0916b71b5e00ba16a40ba582bbfc392511322e6f"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "74ff662fff20b0ad70f8da40e230318575b9a7c5f54ac26861897a258a90d0d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.powerpc64le-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "51ae9cceb0f342117cf7afacf3e8df8288caccdb"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "6b2d1e3388f2022ab179c63e67bc7386ea516ecf8771974c0c4c144248161ab2"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.x86_64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "2dd13e86da5fa47bb260df895d86368d68d273e5"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "5b26d589bf451c27387470ebe36b7ada7f126232d1f59a73f5415a556bb72f4d"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.x86_64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "7d46511a75816f7c10bd5b9e496f23b65032141b"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "36b9349b114a5c53bc3db886e5d08c7b959585dcb692980471ac387e5e68d373"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.x86_64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "8c373a8c0e4f9a13aa4016cf607f90ccdee49970"
os = "freebsd"

    [[OpenLibm.download]]
    sha256 = "0a2a5cb219245001a40ada21b71d45b18693f8360e4da18aea370dae84e7447e"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.x86_64-unknown-freebsd.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "213201430fc09895769712a39a50883de4b23fd8"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "a9abdf1cc795031f224eb598b1e279673f20ea9cdc94debf2e4b2615ae4e85ad"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.3+0/OpenLibm.v0.7.3.x86_64-w64-mingw32.tar.gz"
