[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "0ca2cb0059dedbe8a3ef1b28e5074a2fe37ffde5"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "a408a8ff65adb65528e5d97364a415778582e602cbefef69aa3beb42c379c289"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.aarch64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "cfa69417f5bc4ec9f6370615a91d2b79f81043ee"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "29bad867f1e38c468fd07f5cf7ca613b8d401b8b0718221a4252285fa69a139f"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.aarch64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "dece607fc537e2861bbbc3a99865c105f80b268d"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "239bce2a597a777d478db49d958b8875050ea8e8d0865a9f211d2ce73d030e22"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.aarch64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c536dec505334e5870dbcac83041d015a81d80ff"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "c6e8331b13981cc80bbfe4d184dfcdcc8df9dd6d555c31606bf01f0d6f2b59c8"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.armv6l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e19b90baf33847ac191a2cb021b63f902714fbc"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "67b97ba77afa26db541b308919a3a3e298f621434cf5f822f905d50c1921a591"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.armv6l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "28f38510e089090bfd714a0fea3faae82a7fcdb8"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "aa600ed39bb83754237049f910cda1334c55d31e089425f8156e736dd5f55bc1"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.armv7l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "adf3ab14b1e5d116e5027190b4fa3d113668bb27"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "c4db43676cafb05a9aab821c360393f62cb0a3fb7c9f98304acace49eef15824"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.armv7l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "f7ca5d81a1350d916c46a0dcb8014e8d75bdf4c8"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "45ddcb38068add71bc8798ec1374cf959a9c997fe7d0dbf638578cad9d436734"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.i686-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "73e4618ac4f99ae33c1cde1e816e4a210b3f00c1"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "c1d0fda68eb6159c029c2923dd56c62ddd8a053a9028dbde7bf8e164e19cb102"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.i686-linux-musl.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "5175d2ab4490212a7d5cb3d760d5b9ec37b1e2ac"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "5c63627e51f554dfad64383391283c1f5a60ea4c059030d16f0cb4cfee965d5b"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.i686-w64-mingw32.tar.gz"
[[OpenLibm]]
arch = "powerpc64le"
git-tree-sha1 = "4a25926309e79939e59f108945e9f382748d5312"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "d53743d3e5c41679c23d19b09a535add527b7b7d10bb9ca389237b4dc143c5a5"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.powerpc64le-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "42b03f5764b4a98bae17fbed54be05ffef21ed8d"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "fd8b14bf1e375d27aca517a047fa54b83a2911d8f99835267c7ff6e2f27cb440"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.x86_64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "3e6df3d745037b327968ae301826325c45ef9a45"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "70211cc0b8262d48a9293d78d64dd3fe2dcd9d8fb1f5552c53adc24a323b42b6"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.x86_64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "7b2f59fbc2536d297724a2067fbf83a59f16e7bc"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "f2b927e44e1b575cf530d4c2a1f0904fe6ab66d66f3b36b160ba81808d0a96eb"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.x86_64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "2c45633bf246e5930639481aa7941226468a86d9"
os = "freebsd"

    [[OpenLibm.download]]
    sha256 = "f5da1868e63ea267776d9c12b61fc79ae72c94d6556090fa94e7d5c7fe722260"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.x86_64-unknown-freebsd.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "eaadbe0fcba812417b66a232bd66ca361b67cc6d"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "16cf63caff88d36e580900e39a1640995af67c274f73b2c439253e69eb947972"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.4+0/OpenLibm.v0.7.4.x86_64-w64-mingw32.tar.gz"
