[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "c7d14609df628e31aed022c1f594206fe1e229ab"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "e91ef3f62e81ce204279f95028097eeb08729e277e266b237e7f23beeaa7d8a0"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.aarch64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "191b871b6a2b93b88873d251c8904b691cffe08f"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "b3aa20af8a5758e38781d99505df26f889f09bd2c2d2ae5d9911e6b363c8d043"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.aarch64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "4bff5bfc3695f46d3996c7832f51e5f834eb76e9"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "8007ae573af8119421c68e200a444e38fb2a2c288a9748d592645259ba1608b2"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.aarch64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "755a884d1d9ae7876cad9657932bb590cd18c489"
os = "freebsd"

    [[OpenLibm.download]]
    sha256 = "3486d5776325eefa396c44615d1d5e5db9b04edc408a872551686c2e09977101"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.aarch64-unknown-freebsd.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c513879668221c438d1737839cfbe938bd865a18"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "dd9ca8ddc29c9869b91976db6ecefd952ed01398d27f3c0d04e13bd11e714a13"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.armv6l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "32e51ef937d18a9fbf29c917488d98d52edde430"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "89f1c527bf12d8fd520f5380316e0ba02a0047fc440f18e42e618ab43cfd75ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.armv6l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c513879668221c438d1737839cfbe938bd865a18"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "dd9ca8ddc29c9869b91976db6ecefd952ed01398d27f3c0d04e13bd11e714a13"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.armv7l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32e51ef937d18a9fbf29c917488d98d52edde430"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "89f1c527bf12d8fd520f5380316e0ba02a0047fc440f18e42e618ab43cfd75ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.armv7l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "e44c5a1a419e0bbb911b14a6edebacb4d4888fd1"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "877305c535c411668a0ded7fbb745283a963737c632ec93c63ee38d0ecdd8675"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.i686-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "392e534b2e1c06a1a82c0e18b07d1d31c93d2c2c"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "47e28351c8bd6e74a59ff93f8876a724ff9ead81b6a32a0305f8ec06a52e7f44"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.i686-linux-musl.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "cb71d40774fe8491b217e6b228c812763dbece62"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "1c647e96ddb2b71888539a3be93f0aa66210bbce217df7c3a56bd6e43f46554f"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.i686-w64-mingw32.tar.gz"
[[OpenLibm]]
arch = "powerpc64le"
git-tree-sha1 = "79d7f1d2496883c2bcbfd6f37fe329794486fdb4"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "177f7453e73a4348299dac71f1c7badbd1cfd651fdaa4ad904cfaf7e149f9959"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.powerpc64le-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "riscv64"
git-tree-sha1 = "6fd91e2d72c6a8805901324dcb8f8ab6505c7293"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "e1ae1cfb20fec0a7cb8b186d6082e2f525fadec05971cf89bd89dbae91b0aa60"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.riscv64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "ed19d826f8efd323233f1ffdbab51dfa028897df"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "5e99ecebb3f694b24bdb47f728f024a39dcb60969d56aaa168821ea9d1fc9a31"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.x86_64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "f3336b9b61d58013e53e5d9bb2464c258d99735f"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "01b3c0f8cb0cb68bb5add394e8cbffa4dd4d48b487cede747022fa7928fd96b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.x86_64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "9451c173296a38634372a15796e6ef684ce2018c"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[OpenLibm.download]]
    sha256 = "55dc79ad3c22fd3bd48430d73b651cab703a054519ba09234ac10a8dd79f24a6"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "1b005591a91e1e12d8988d0eee0c952881c2031a"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "c25b30f814720164a8b50796fda7ad097610ba7887862745bd9f8c09df4ff4dd"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.x86_64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "780c20d19f6bd4357bdd6ab90314970f5097899d"
os = "freebsd"

    [[OpenLibm.download]]
    sha256 = "a44b98bb9c97eb0c74dbf64510ad23eadd94ecd90ab426d7b790d11ab19500ce"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "b0ad35daabde60be36a9ec2ff446b3b233ab157a"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "2c29efc8b8873d132d47221d6c7d8dc51316d021434fcdd16fdc1603d4ddd647"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.8.1+4/OpenLibm.v0.8.1.x86_64-w64-mingw32.tar.gz"
