[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "bc12f798b70debfa9bbf4fa56e112a473f159106"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "01741c135e7b7fe46542dfb97e8c02c356d625a184f0ef1681953d9a293da485"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.aarch64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "1cecef2345e11c5a1f5c91bc3080a985eaf825f2"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "fa59a9d9213284c702d70f53f5cd0ff7325ebdadf743b1338defa045dd528792"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.aarch64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "aarch64"
git-tree-sha1 = "8c4a6e0b2158a47d067c0ce0e35e2d193dca04bf"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "5827d2833693a4f4b5ed3f0219ae67eb9e635c2f733d78907d6ee2229231ab80"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.aarch64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "08d32c91060b10c2e5a649c22b6b5aa3894d6719"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "5fdee6e4f5af8bbfa93420130b420c09c6ad5c0588860d042d35510409fe1483"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.armv6l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ff21e85585f4a55a24f80e337b6a3fb2d0451fe"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "c9f82ac6101bfd92e62624f7a3babe2227f9fd925d59a188f69b12eebfb24691"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.armv6l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "262c8c1bdbc7b83d01cff3d8bdcbda24b51a0f29"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "2524463e587643c8bb82f8ec4b546a2bf220fc93e30dce0eb23c1c70fd96a848"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.armv7l-linux-gnueabihf.tar.gz"
[[OpenLibm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "44a010ef889826f2500126f2cc2a878d9826cb61"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "53cf23e1395baf8f708699c0a38a29f5bcf4894fce5fe3b471190fe476638caf"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.armv7l-linux-musleabihf.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "7fcfa4162f30e807c91d8e813969a11548a71708"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "b7bc10d568a4a457c6740a3a57364a4dd6cdf7b326214dfe90f9e314adb7b230"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.i686-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "797a518e70eeafadb11dc06efcdb2c9f6064cc66"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "3e7499c7c7d81b457779d5ad6b9bd762e49eba5148c385ebedb90715957f9eb9"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.i686-linux-musl.tar.gz"
[[OpenLibm]]
arch = "i686"
git-tree-sha1 = "4d497f470c4115444e65f2c93014443456c19aa5"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "3eee666fce7938fc9d682850ad8e38a6766d06474727b38c84c4541a8c1749e2"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.i686-w64-mingw32.tar.gz"
[[OpenLibm]]
arch = "powerpc64le"
git-tree-sha1 = "4021401fff3c0d94db28dd2bb8ec1410b58fd9b3"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "76ad8fac93b3caf0d6c3221e5fe8f90f947cd2edc5695747d673d739793f7893"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.powerpc64le-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "3df54bcba4e4939fc29f7d874f8417b188a19398"
os = "macos"

    [[OpenLibm.download]]
    sha256 = "5d38273dbd506e410f0d11e5ca8e023bd5c1dcf884e7dc72bed1afce8a8213d5"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.x86_64-apple-darwin.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "31f56016ddb0fe5be82580ebef694ec5e9241277"
libc = "glibc"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "06e8b2a0cfa8ef3b59bd055acd7b3dd34c9484c311cf3ed32bbe169fda5bb977"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.x86_64-linux-gnu.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "94cfee036e42fec73d7e2260e9cf2d83fbf8aef1"
libc = "musl"
os = "linux"

    [[OpenLibm.download]]
    sha256 = "58dd55db3e6934cfee68fba7b70462254154ea6bdf64edc8ad0f550e62d12250"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.x86_64-linux-musl.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "b1c0bb9c005066795fbf57d50e4e56d7d93bac13"
os = "freebsd"

    [[OpenLibm.download]]
    sha256 = "879e69c2716fd5d920d3253dd38a73532c9c4d114317be361411f1224900437e"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.x86_64-unknown-freebsd.tar.gz"
[[OpenLibm]]
arch = "x86_64"
git-tree-sha1 = "11a4f8b9769fd6ada26312cb483236b0e14eb842"
os = "windows"

    [[OpenLibm.download]]
    sha256 = "70a06e93fb866cb7717febafbca3c7cbf0c458b376659707be81e9f799a4a123"
    url = "https://github.com/JuliaBinaryWrappers/OpenLibm_jll.jl/releases/download/OpenLibm-v0.7.5+0/OpenLibm.v0.7.5.x86_64-w64-mingw32.tar.gz"
